apiVersion: v1
kind: Service
metadata:
  name: test-app-service
spec:
  selector:
    tier: frontend
    app: test-app
  type: NodePort
  ports:
    - port: 7080
      targetPort: 80
      nodePort: 30080